apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-inference-server
  labels:
    app: triton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      containers:
      - name: triton
        image: "nvcr.io/nvidia/tritonserver:25.07-py3-igpu"
        args: ["tritonserver", "--model-repository=/models"]
        ports:
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8002
        volumeMounts:
        - name: model-repository
          mountPath: /models
        resources:
          limits:
            nvidia.com/gpu: 1
      volumes:
      - name: model-repository
        hostPath:
          path: /models
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: triton
  ports:
  - protocol: TCP
    name: http
    port: 8000
    targetPort: 8000
  - protocol: TCP
    name: grpc
    port: 8001
    targetPort: 8001
  - protocol: TCP
    name: metrics
    port: 8002
    targetPort: 8002
