services:
  jetson-stats:
    build:
      context: .
      dockerfile: Containerfile.jetson-stats
    privileged: true
    pid: host
    volumes:
      - "/run:/run"
      - "/sys:/sys"
      - "/var:/var"
      - "/etc/fstab:/etc/fstab"
      - "/etc/nvpmodel:/etc/nvpmodel"
      - "/etc/nvpmodel.conf:/etc/nvpmodel.conf"
