FROM docker.io/rockylinux/rockylinux:9.4
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN dnf -y install git which && dnf clean all

RUN uv venv /app && VIRTUAL_ENV=/app uv pip install git+https://github.com/NickCao/jetson_stats_node_exporter
ENTRYPOINT /app/bin/python -m jetson_stats_node_exporter
