ARG BASE_IMAGE=quay.io/redhat-et/rhel-bootc-tegra:base
FROM ${BASE_IMAGE}
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ARG HF_REPOS
RUN <<DOWNLOAD
for REPO in ${HF_REPOS}; do
  uvx --no-cache --from "huggingface_hub[cli]" huggingface-cli download \
    ${REPO} --local-dir /usr/share/huggingface/${REPO}
done
DOWNLOAD
