ARG VLLM_WHEEL_ARTIFACT
FROM ${VLLM_WHEEL_ARTIFACT} as vllm
ARG TORCH_WHEEL_ARTIFACT
FROM ${TORCH_WHEEL_ARTIFACT} as torch
ARG TORCH_LIB_ARTIFACT
FROM ${TORCH_LIB_ARTIFACT} as torch-lib

ARG BASE_IMAGE
FROM ${BASE_IMAGE}
RUN dnf install -y python3.11 python3.11-devel gcc ninja-build && dnf clean all
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
COPY --from=torch-lib /lib /torch/lib
ENV UV_PYTHON=python3.11 VIRTUAL_ENV=/app LD_LIBRARY_PATH=/torch/lib
RUN \
  --mount=from=vllm,target=/mnt/vllm \
  --mount=from=torch,target=/mnt/torch \
  <<EOF
set -euxo pipefail
export UV_CACHE_DIR=/tmp/uv
uv venv /app
uv pip install \
  /mnt/torch/wheels/*.whl \
  torchvision \
  torchaudio \
  pytorch-triton \
  --index-url https://download.pytorch.org/whl/cu128
uv pip install \
  /mnt/vllm/wheels/*.whl
rm -r /tmp/uv
EOF

