ARG BASE_IMAGE=quay.io/redhat-et/rhel-bootc-tegra:base
FROM ${BASE_IMAGE}

ADD --chmod=0555 https://gitlab.com/fedora/bootc/examples/-/raw/main/physically-bound-images/embed_image.sh \
      /opt/physically-bound-images/embed_image.sh
ADD --chmod=0555 https://gitlab.com/fedora/bootc/examples/-/raw/main/physically-bound-images/copy_embedded_images.sh \
      /opt/physically-bound-images/copy_embedded_images.sh

RUN cat <<EOF > /etc/systemd/system/copy-embedded-images.service
[Unit]
Description=Copy embedded images
Requires=basic.target network-online.target
After=basic.target network-online.target

[Service]
Type=oneshot
ExecStart=/opt/physically-bound-images/copy_embedded_images.sh
RemainAfterExit=yes

[Install]
EOF
RUN systemctl enable copy-embedded-images

ARG APP_IMAGES
ARG DAT_IMAGES
RUN <<PULL
for IMAGE in ${APP_IMAGES}; do
  /opt/physically-bound-images/embed_image.sh ${IMAGE}
done
for IMAGE in ${DAT_IMAGES}; do
  /opt/physically-bound-images/embed_image.sh ${IMAGE} --multi-arch=all
done
PULL
