# Installs ARM Ollama in a container

ARG BASE_IMAGE

FROM ${BASE_IMAGE}

ARG MODELS

RUN <<EOF
curl -L https://ollama.com/download/ollama-linux-arm64.tgz -o ollama-linux-arm64.tgz
tar -C /usr -xzf ollama-linux-arm64.tgz
EOF

RUN <<EOF
ollama serve &
for model in ${MODELS}; do
	ollama pull $model
done
kill %1
EOF
