name: "Build all Jetson Servers"
on:
  workflow_dispatch:
jobs:
  build-ollama:
    uses: ./.github/workflows/build-ollama.yml
    secrets: inherit
    with:
      models: gemma3:4b
  
  build-vllm:
    uses: ./.github/workflows/build-vllm.yml
    secrets: inherit
    with:
      models: ibm-granite/granite-vision-3.3-2b ibm-granite/granite-3.3-2b-instruct

  build-triton:
    uses: ./.github/workflows/build-triton.yml
    secrets: inherit

  build-triton-microshift:
    uses: ./.github/workflows/build-microshift.yml
    secrets: inherit
    needs: build-triton
    with:
      input-image: ${{ vars.DEST_REGISTRY_HOST }}/${{ vars.DEST_REGISTRY_REPO }}:triton
      tag-list: "triton-microshift"
      resource-definitions: "/repo/triton/microshift/triton.yml"
