name: "Build Ollama Server"
on:
  workflow_dispatch:
    inputs:
      models:
        type: string
        required: true
        description: "models (see README.md)"
        default: "gemma3:4b"
  workflow_call:
    inputs:
      models:
        type: string
        required: true

jobs:
  build-ollama-container:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    with:
      containerfile: ollama/Containerfile.ollama
      tag-list: "ollama-worker"
      dest-image: ${{ vars.ARTIFACT_REGISTRY_REPO }}
      dest-host: ${{ vars.ARTIFACT_REGISTRY_HOST }}
      build-args: |
        BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.6
        MODELS=${{ inputs.models }}

  build-ollama:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    needs: build-ollama-container
    with:
      containerfile: tegra/Containerfile.podman
      dest-image: "redhat-et/rhel-bootc-tegra"
      tag-list: "ollama"
      build-args: |
        APP_IMAGES=${{ needs.build-ollama-container.outputs.dest-reference }}

  build-ollama-raw:
    uses: ./.github/workflows/build-rhel-bootc-raw-image.yml
    secrets: inherit
    needs: build-ollama
    with:
      config-file: ./tegra/config.toml
      src-reference: ${{ needs.build-ollama.outputs.dest-reference }}
