name: Build Triton Server
on:
  workflow_dispatch:
    inputs:
      base-reference:
        type: string
        required: false
        description: "Base bootc container reference (can be left blank)"
  workflow_call:
    inputs:
      base-reference:
        type: string
        required: false

jobs:
  base-reference:
    uses: ./.github/workflows/get-base-reference.yml
    secrets: inherit
    with:
      base-reference: ${{ inputs.base-reference }}

  build-engine:
    uses: ./.github/workflows/run-jumpstarter-workflow.yml
    secrets: inherit
    with:
      jumpstarter-selector: ${{ vars.JUMPSTARTER_SELECTOR }}
      image-url: ${{ vars.DEST_REGISTRY_HOST }}/${{ vars.DEST_REGISTRY_REPO }}:base-raw
      workflow-cmd: |
        bash triton/build/jmp-build-engine.sh \
          ${{ vars.ARTIFACT_REGISTRY_HOST }}/${{ vars.ARTIFACT_REGISTRY_REPO }}:onnx-repository \
          ${{ vars.ARTIFACT_REGISTRY_HOST }}/${{ vars.ARTIFACT_REGISTRY_REPO }}:plan-repository

  build-triton-base:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    needs: base-reference
    with:
      containerfile: tegra/Containerfile.podman
      dest-host: ${{ vars.ARTIFACT_REGISTRY_HOST }}
      dest-image: ${{ vars.ARTIFACT_REGISTRY_REPO }}
      tag-list: "triton-base"
      build-args: |
        BASE_IMAGE=${{ needs.base-reference.outputs.base-reference }}
        APP_IMAGES=nvcr.io/nvidia/tritonserver:25.05-py3-igpu

  build-triton:
    needs: [build-engine, build-triton-base]
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    with:
      containerfile: triton/build/Containerfile.triton
      dest-host: ${{ vars.DEST_REGISTRY_HOST }}
      dest-image: ${{ vars.DEST_REGISTRY_REPO }}
      tag-list: "triton"
      extra-args: --secret id=podman-auth,src=/run/containers/0/auth.json 
      build-args: |
        BASE_IMAGE=${{ needs.build-triton-base.outputs.dest-reference }}
        PLAN_REPOSITORY=${{ vars.ARTIFACT_REGISTRY_HOST }}/${{ vars.ARTIFACT_REGISTRY_REPO }}:plan-repository

  build-triton-raw:
    uses: ./.github/workflows/build-rhel-bootc-raw-image.yml
    secrets: inherit
    needs: build-triton
    with:
      config-file: ./tegra/config.toml
      src-reference: ${{ needs.build-triton.outputs.dest-reference }}
