name: Add MicroShift to Bootc Image
on:
  workflow_dispatch:
    inputs:
      resource_definitions:
        type: string
        description: "See README.md"
        required: false
      input_image:
        type: string
        description: "URL of image to add Microshift to"
        required: true
      tag_list:
        type: string
        description: "Tag list of new image"
        required: true
jobs:
  build-microshift:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    with:
      containerfile: tegra/Containerfile.microshift
      dest-host: ${{ vars.DEST_REGISTRY_HOST }}
      dest-image: ${{ vars.DEST_REGISTRY_REPO }}
      tag-list: ${{ inputs.tag_list }}
      extra-args: |
        --secret id=openshift-pull-secret,src=openshift-pull-secret.json
        --volume /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/repo
      build-args: |
        BASE_IMAGE=${{ inputs.input_image }}
        RESOURCE_DEFINITIONS=${{ inputs.resource_definitions }}

  build-microshift-raw:
    uses: ./.github/workflows/build-rhel-bootc-raw-image.yml
    secrets: inherit
    needs: build-microshift
    with:
      config-file: ./tegra/config.toml
      src-reference: ${{ needs.build-microshift.outputs.dest_reference }}

