name: Build Inference Server on RHEL Bootc Nvidia Tegra
on:
  workflow_dispatch:
    inputs:
      base-reference:
        type: string
        required: false
  workflow_call:
    inputs:
      base-reference:
        type: string
        required: false

jobs:
  base-reference:
    uses: ./.github/workflows/get-base-reference.yml
    secrets: inherit
    with:
      base-reference: ${{ inputs.base-reference }}

  build-engine:
    uses: ./.github/workflows/run-jumpstarter-workflow.yml
    secrets: inherit
    with:
      jumpstarter-selector: ${{ vars.JUMPSTARTER_SELECTOR }}
      image-url: ${{ needs.base-reference.outputs.base-reference }}-raw
      workflow-cmd: |
        bash inference/build/jmp-build-engine.sh \
          ${{ vars.ARTIFACT_REGISTRY_HOST }}/${{ vars.ARTIFACT_REGISTRY_REPO }}:onnx-repository \
          ${{ vars.ARTIFACT_REGISTRY_HOST }}/${{ vars.ARTIFACT_REGISTRY_REPO }}:plan-repository

  build-intermediate-triton:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    with:
      containerfile: tegra/Containerfile.podman
      dest-host: ${{ vars.ARTIFACT_REGISTRY_HOST }}
      dest-image: ${{ vars.ARTIFACT_REGISTRY_REPO }}
      tag-list: "triton-inference-server-intermediate"
      build-args: |
        BASE_IMAGE=${{ inputs.base-image }}
        APP_IMAGES=nvcr.io/nvidia/tritonserver:25.05-py3-igpu

  build-triton:
    needs: [build-engine, build-intermediate-triton]
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    with:
      containerfile: inference/build/Containerfile.triton
      dest-host: ${{ vars.DEST_REGISTRY_HOST }}
      dest-image: ${{ vars.DEST_REGISTRY_REPO }}
      tag-list: "triton-inference-server"
      extra-args: --secret id=podman-auth,src=/run/containers/0/auth.json 
      build-args: |
        BASE_IMAGE=${{ vars.ARTIFACT_REGISTRY_HOST }}/${{ vars.ARTIFACT_REGISTRY_REPO }}:triton-inference-server-intermediate
        PLAN_REPOSITORY=${{ vars.ARTIFACT_REGISTRY_HOST }}/${{ vars.ARTIFACT_REGISTRY_REPO }}:plan-repository

  build-triton-raw:
    if: inputs.build_microshift == false
    uses: ./.github/workflows/build-rhel-bootc-raw-image.yml
    secrets: inherit
    needs: build-triton
    with:
      config-file: ./tegra/config.toml
      src-reference: ${{ needs.build-triton.outputs.dest-reference }}
