name: Build Trtexec Image for Model Conversion
on:
  workflow_dispatch:
jobs:
  build-trtexec:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    with:
      containerfile: tegra/Containerfile.podman
      dest-host: ${{ vars.DEST_REGISTRY_HOST }}
      dest-image: ${{ vars.DEST_REGISTRY_REPO }}
      tag-list: "tensorrt"
      build-args: |
        BASE_IMAGE=quay.io/redhat-et/rhel-bootc-tegra:base
        APP_IMAGES=nvcr.io/nvidia/trtexec:25.05-py3-igpu

  build-trtexec-raw:
    uses: ./.github/workflows/build-rhel-bootc-raw-image.yml
    secrets: inherit
    needs: build-trtexec
    with:
      config-file: ./tegra/config.toml
      src-reference: ${{ needs.build-trtexec.outputs.dest-reference }}
