name: "Build Empty Microshift Server"
on:
  workflow_dispatch:
    inputs:
      base-image:
        type: string
        required: true
        default: quay.io/redhat-user-workloads/octo-edge-tenant/rhel-bootc-jetson-rhel94:latest
        description: Base Image
      tag-list:
        type: string
        required: true
        description: Tag List
  workflow_call:

jobs:
  build-empty:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    with:
      containerfile: tegra/Containerfile.podman
      dest-image: "redhat-et/rhel-bootc-tegra"
      tag-list: "empty"
      build-args: |
        BASE_IMAGE=${{ inputs.base-image }}

  build-microshift:
    uses: ./.github/workflows/build-microshift.yml
    secrets: inherit
    needs: build-empty
    with:
      input-image: ${{ needs.build-empty.outputs.dest-reference }}
      tag-list: ${{ inputs.tag-list }}
