name: Build Minimal MicroShift Server on RHEL Bootc Nvidia Tegra
on:
  workflow_dispatch:
jobs:
  build-podman:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    with:
      containerfile: tegra/Containerfile.podman
      dest-host: ${{ vars.ARTIFACT_REGISTRY_HOST }}
      dest-image: ${{ vars.ARTIFACT_REGISTRY_REPO }}
      tag-list: "python3.12"
      extra-args: |
        --secret id=openshift-pull-secret,src=openshift-pull-secret.json
        --volume /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/repo
      build-args: |
        BASE_IMAGE=quay.io/redhat-et/rhel-bootc-tegra:base
        APP_IMAGES=python:3.12

  build-microshift:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    needs: build-podman
    with:
      containerfile: tegra/Containerfile.microshift
      dest-host: ${{ vars.ARTIFACT_REGISTRY_HOST }}
      dest-image: ${{ vars.ARTIFACT_REGISTRY_REPO }}
      tag-list: "microshift"
      extra-args: |
        --secret id=openshift-pull-secret,src=openshift-pull-secret.json
        --volume /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}:/repo
      build-args: |
        BASE_IMAGE=${{ needs.build-podman.outputs.dest-reference }}
        RESOURCE_DEFINITIONS=

  build-raw:
    uses: ./.github/workflows/build-rhel-bootc-raw-image.yml
    secrets: inherit
    needs: build-microshift
    with:
      config-file: ./tegra/config.toml
      src-reference: ${{ needs.build-microshift.outputs.dest-reference }}

  flash-image:
    uses: ./.github/workflows/run-jumpstarter-workflow.yml
    secrets: inherit
    needs: build-raw
    with:
      workflow-cmd: echo hello
      image-url: ${{ needs.build-raw.outputs.dest-reference }}
      jumpstarter-selector: name=majopela-orin-nx
