# Reference: https://github.com/redhat-cop/redhat-image-mode-actions
name: Build RHEL bootc image
on:
  workflow_call:
    inputs:
      containerfile:
        type: string
        required: true
      dest-image:
        type: string
        required: true
      dest-host:
        type: string
        required: false
        default: quay.io
      build-args:
        type: string
        required: false
      tag-list:
        type: string
        required: true
      runs-on:
        type: string
        default: ubuntu-24.04-arm
      extra-args:
        type: string
        required: false
    outputs:
      dest-reference:
        value: ${{ jobs.rhel-bootc-image-build.outputs.dest-reference }}
      dest-digest:
        # a bit misleadingly, this also includes the host/repo URL along with the @sha
        value: ${{ jobs.rhel-bootc-image-build.outputs.dest-digest }}

jobs:
  rhel-bootc-image-build:
    name: Build RHEL bootc image
    runs-on: ${{ inputs.runs-on }}
    outputs:
      dest-digest: "${{ inputs.dest-host }}/${{ inputs.dest-image }}@${{ steps.push-to-ghcr.outputs.digest }}"
      dest-reference: "${{ steps.push-to-ghcr.outputs.registry-path }}@${{ steps.push-to-ghcr.outputs.digest }}"
    env:
      # Disable Subscription Manager container passthrough
      SMDEV_CONTAINER_OFF: 1

    container:
      image: registry.access.redhat.com/ubi10/ubi
      options: --privileged --device /dev/nvme0n1
    permissions:
      contents: write
      packages: write

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Get container tools in UBI builder
        run: dnf -y install podman buildah skopeo jq

      - name: Disable container image signature verification
        run: |
          jq "del(.transports)" /etc/containers/policy.json > /etc/containers/policy.json.new
          mv /etc/containers/policy.json.new /etc/containers/policy.json

      - name: Free up disk space
        run: |
          dnf config-manager --add-repo https://repo.almalinux.org/almalinux/10/BaseOS/aarch64/os/
          dnf install xfsprogs -y --nogpgcheck
          mkfs.xfs /dev/nvme0n1
          mkdir -p              /var/lib/containers
          mount    /dev/nvme0n1 /var/lib/containers

      - name: Access a subscription via activation key
        run: subscription-manager register --org=${{ secrets.RHT_ORGID }} --activationkey=${{ secrets.RHT_ACT_KEY }}

      # workaround for https://github.com/redhat-actions/podman-login/issues/42 since the docker config from the host doesn't come up to the container
      - name: Workaround open podman-login action issue
        env:
          auth: "{ \"auths\": {} }"
        run: |
          mkdir -p $HOME/.docker
          echo $auth > $HOME/.docker/config.json

      - name: Log in to the RHT terms based registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ vars.SOURCE_REGISTRY_HOST }}
          username: ${{ secrets.SOURCE_REGISTRY_USER }}
          password: ${{ secrets.SOURCE_REGISTRY_PASSWORD }}
          auth_file_path: /run/containers/0/auth.json

      - name: Log in to the Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ vars.DEST_REGISTRY_HOST }}
          username: ${{ secrets.DEST_REGISTRY_USER }}
          password: ${{ secrets.DEST_REGISTRY_PASSWORD }}
          auth_file_path: /run/containers/0/auth.json

      - name: Log in to the Artifact registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ vars.ARTIFACT_REGISTRY_HOST }}
          username: ${{ secrets.ARTIFACT_REGISTRY_USER }}
          password: ${{ secrets.ARTIFACT_REGISTRY_PASSWORD }}
          auth_file_path: /run/containers/0/auth.json
          logout: false

      - name: Prepare OpenShift Pull Secret
        run: |
          cat  <<EOF > openshift-pull-secret.json
          ${{ secrets.OPENSHIFT_PULL_SECRET }}
          EOF

      - name: Use buildah bud to create the image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ inputs.dest-image }}
          tags: ${{ inputs.tag-list }}
          containerfiles: ${{ inputs.containerfile }}
          build-args: ${{ inputs.build-args }}
          extra-args: ${{ inputs.extra-args }}

      - name: Push to Container Repository
        id: push-to-ghcr
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ inputs.dest-host }}

      - name: Clean up the subscription
        if: always()
        run: subscription-manager unregister
