name: Build Inference Server on RHEL Bootc Nvidia Tegra
on:
  workflow_dispatch:
#  push:
#    branches:
#      - "main"
#    paths:
#      - "tegra/**"
#      - ".github/workflows/build-rhel-bootc-image.yml"
#      - ".github/workflows/build-rhel-bootc-raw-image.yml"
#      - ".github/workflows/tegra.yml"
  workflow_call:
jobs:
  create-engine:
    uses: ./.github/workflows/run-jumpstarter-workflow.yml
    secrets: inherit
    with:
      jumpstarter-selector: name=nvidia-jetson-nx-orin-01-khw-eng-bos2-beaker
      image-url: #quay.io/redhat-et/rhel-bootc-tegra:tensorrt-raw
      workflow-cmd: bash inference/jmp-build-engine.sh quay.io/redhat-et/rhel-bootc-tegra-artifacts:model-onnx quay.io/redhat-et/rhel-bootc-tegra-artifacts:model-plan

  build-intermediate-tis:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    with:
      containerfile: tegra/Containerfile.podman
      dest-image: "redhat-et/rhel-bootc-tegra-artifacts"
      tag-list: "triton-inference-server-intermediate"
      build-args: |
        BASE_IMAGE=quay.io/redhat-et/rhel-bootc-tegra:base
        APP_IMAGES=nvcr.io/nvidia/tritonserver:25.05-py3-igpu nvcr.io/nvidia/tritonserver:25.05-py3-igpu-sdk

  build-tegra-tis:
    # needs: [create-engine, build-intermediate-tis]
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    with:
      containerfile: inference/Containerfile.tis
      dest-image: "redhat-et/rhel-bootc-tegra"
      tag-list: "triton-inference-server"
      build-args: |
        BASE_IMAGE=quay.io/redhat-et/rhel-bootc-tegra-artifacts:triton-inference-server-intermediate
        PLAN_ARTIFACT_URL=quay.io/redhat-et/rhel-bootc-tegra-artifacts:model-plan

  build-tis-raw:
    uses: ./.github/workflows/build-rhel-bootc-raw-image.yml
    secrets: inherit
    needs: build-tegra-tis
    with:
      config-file: ./tegra/config.toml
      src-reference: ${{ needs.build-tegra-tis.outputs.dest-reference }}

  test-tis:
    uses: ./.github/workflows/run-jumpstarter-workflow.yml
    secrets: inherit
    needs: build-tis-raw
    with:
      jumpstarter-selector: name=nvidia-jetson-nx-orin-01-khw-eng-bos2-beaker
      image-url: ${{ needs.build-tis-raw.outputs.dest-reference }}
      workflow-cmd: python3 inference/jmp-test-tis.py
