name: Build Base Bootc Image
on:
  workflow_dispatch:
jobs:
  build-tegra-base:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    with:
      containerfile: tegra/Containerfile.base
      dest-image: "redhat-et/rhel-bootc-tegra"
      tag-list: "base"

  build-tegra-base-image:
    uses: ./.github/workflows/build-rhel-bootc-raw-image.yml
    secrets: inherit
    needs: build-tegra-base
    with:
      config-file: ./tegra/config.toml
      src-reference: ${{ needs.build-tegra-base.outputs.dest-reference }}
