name: Build Inference Server on RHEL Bootc Nvidia Tegra
on:
  workflow_dispatch:
#  push:
#    branches:
#      - "main"
#    paths:
#      - "tegra/**"
#      - ".github/workflows/build-rhel-bootc-image.yml"
#      - ".github/workflows/build-rhel-bootc-raw-image.yml"
#      - ".github/workflows/tegra.yml"
jobs:
  build-tegra-trtexec:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    with:
      containerfile: inference/Containerfile.trtexec
      dest-image: "redhat-et/rhel-bootc-tegra"
      tag-list: "builder-tensorrt"
      build-args: |
        BASE_IMAGE=quay.io/redhat-et/rhel-bootc-tegra:base
        APP_IMAGES=nvcr.io/nvidia/tensorrt:25.05-py3-igpu

  build-tegra-trtexec-disk-image:
    uses: ./.github/workflows/build-rhel-bootc-raw-image.yml
    secrets: inherit
    needs: build-tegra-trtexec
    with:
      config-file: ./inference/config.toml
      src-reference: ${{ needs.build-tegra-trtexec.outputs.dest-reference }}

  create-engine:
    uses: ./.github/workflows/run-jumpstarter-workflow.yml
    secrets: inherit
    needs: build-tegra-trtexec-disk-image
    with:
      jumpstarter-selector: name=nvidia-jetson-nx-orin-01-khw-eng-bos2-beaker
      image-url: ${{ needs.build-tegra-trtexec-disk-image.outputs.dest-reference }}
      workflow-cmd: inference/jmp-build-engine.sh

  build-intermediate-tis:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    with:
      containerfile: tegra/Containerfile.podman
      dest-image: "redhat-et/rhel-bootc-tegra"
      tag-list: "triton-inference-server-intermediate"
      build-args: |
        BASE_IMAGE=quay.io/redhat-et/rhel-bootc-tegra:base
        APP_IMAGES=nvcr.io/nvidia/tritonserver:25.05-py3-igpu-sdk

  build-tegra-tis:
    needs: create-engine
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    env:
      SECRET_BUILD_ARGS: |
        PLAN_REGISTRY_USER=${{ secrets.DEST_REGISTRY_USER }}
        PLAN_REGISTRY_PASSWORD=${{ secrets.DEST_REGISTRY_PASSWORD }}
    with:
      containerfile: inference/Containerfile.tis
      dest-image: "redhat-et/rhel-bootc-tegra"
      tag-list: "triton-inference-server"
      build-args: |
        BASE_IMAGE=${{ needs.build-intermediate-tis.outputs.dest-reference }}
        PLAN_ARTIFACT_URL=quay.io/redhat-et/rhel-bootc-tegra:model-plan 
        PLAN_REGISTRY=quay.io

  build-tis-raw:
    uses: ./.github/workflows/build-rhel-bootc-raw-image.yml
    secrets: inherit
    needs: build-tegra-tis
    with:
      config-file: ./inference/config.toml
      src-reference: ${{ needs.build-tegra-tis.outputs.dest-reference }}

  test-tis:
    uses: ./.github/workflows/run-jumpstarter-workflow.yml
    secrets: inherit
    needs: built-tis-raw
    with:
      jumpstarter-selector: name=nvidia-jetson-nx-orin-01-khw-eng-bos2-beaker
      image-url: ${{ needs.build-tis-raw.outputs.dest-reference }}
      workflow-cmd: python3 inference/jmp-test-tis.py
