name: Manual Jumpstarter Workflow
on:
  workflow_dispatch:
    inputs:
      jumpstarter-selector:
        required: true
        type: string
      image-url:
        description: 'Container image URL to deploy'
        required: false
        type: string
        default: ''
      workflow-cmd:
        description: 'Command to execute on the device'
        required: false
        type: string
        default: 'echo hello'
jobs:
  deploy:
    uses: ./.github/workflows/run-jumpstarter-workflow.yml
    with:
      image-url: ${{ inputs.image-url }}
      jumpstarter-selector: ${{ inputs.jumpstarter-selector }}
      workflow-cmd: ${{ inputs.workflow-cmd }}
    secrets: inherit 
