name: Publish Python Wheels to GitHub Pages
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: fedora:42
      options: --privileged --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          dnf update -y
          dnf install -y podman

      - name: Pull OCI artifact with wheels
        id: extract-wheels
        run: |
          podman artifact pull quay.io/vraiti/artifacts:jetson-wheels 
          podman artifact extract quay.io/vraiti/artifacts:jetson-wheels wheels.tar
          tar xf wheels.tar

      - name: Upload wheels artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: wheels

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

    


