name: Run Jumpstarter Workflow
on:
  workflow_call:
    inputs:
      image-url:
        type: string
        required: true
      jumpstarter-selector:
        type: string
        required: true
      workflow-cmd:
        type: string
        required: true
jobs:
  jumpstarter-workflow:
    runs-on: ubuntu-24.04-arm
    container:
      image: docker.io/fedora:42
      options: --privileged --device /dev/nvme0n1
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install podman
        run: dnf -y install podman jq xz python3.12 git make
      - name: Free up disk space
        run: |
          dnf install xfsprogs -y
          mkfs.xfs /dev/nvme0n1
          mkdir -p              /var/lib/containers
          mount    /dev/nvme0n1 /var/lib/containers
      - name: Workaround open podman-login action issue
        env:
          auth: "{ \"auths\": {} }"
        run: |
          mkdir -p $HOME/.docker
          echo $auth > $HOME/.docker/config.json
      - name: Log in to the Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ vars.DEST_REGISTRY_HOST }}
          username: ${{ secrets.DEST_REGISTRY_USER }}
          password: ${{ secrets.DEST_REGISTRY_PASSWORD }}
          auth_file_path: /run/containers/0/auth.json
      - name: Log in to the Artifact registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ vars.ARTIFACT_REGISTRY_HOST }}
          username: ${{ secrets.ARTIFACT_REGISTRY_USER }}
          password: ${{ secrets.ARTIFACT_REGISTRY_PASSWORD }}
          auth_file_path: /run/containers/0/auth.json
          logout: false
      - name: Install Jumpstarter
        run: |
          git clone https://github.com/jumpstarter-dev/jumpstarter.git
          make -C jumpstarter sync

          source jumpstarter/.venv/bin/activate

          mkdir -p ~/.config/jumpstarter/clients
          cat <<EOF > ~/.config/jumpstarter/clients/default.yaml
          ${{ secrets.JUMPSTARTER_CLIENT_CONFIG }}
          EOF

          jmp config client use default

      - name: Acquire lease
        run: |
          source jumpstarter/.venv/bin/activate

          LEASE=$(jmp create lease --selector ${{ inputs.jumpstarter-selector }} --duration 01:00:00 --output name)
          while true; do
            EXPORTER=$(jmp get leases -o json | jq ".leases[] | select(.name==\"$LEASE\") | .exporter")
            if [[ -n "$EXPORTER" ]]; then
              break
            fi
            sleep 5
          done
          echo "LEASE=$LEASE" >> "$GITHUB_ENV"

      - name: Flash bootc image
        # users have the option to not provide an image, in which case we just run the workflow-cmd
        # I can imagine this may lead to a confusing UX
        if: ${{ inputs.image-url != '' }}
        run: |
          source jumpstarter/.venv/bin/activate

          podman artifact pull    ${{ inputs.image-url }}
          podman artifact extract ${{ inputs.image-url }} image.raw.xz
          jmp shell --lease $LEASE -- j storage dut
          jmp shell --lease $LEASE -- j storage flash --compression xz image.raw.xz

      - name: 
        run: |
          source jumpstarter/.venv/bin/activate

          jmp shell --lease $LEASE -- ${{ inputs.workflow-cmd }}
      - name: Release lease
        if: always()
        run: |
          source jumpstarter/.venv/bin/activate

          jmp delete leases $LEASE
