name: Build RHEL bootc image for Nvidia Tegra
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "tegra/**"
      - ".github/workflows/**"
jobs:
  build-tegra-base:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    with:
      containerfile: tegra/Containerfile.base
      dest-image: "redhat-et/rhel-bootc-tegra"
      tag-list: "base"
  build-tegra-llm:
    uses: ./.github/workflows/build-rhel-bootc-image.yml
    secrets: inherit
    needs: build-tegra-base
    with:
      containerfile: tegra/Containerfile.podman
      dest-image: "redhat-et/rhel-bootc-tegra"
      tag-list: "llm"
      build-args: |
        BASE_IMAGE=${{ needs.build-tegra-base.outputs.dest-reference }}
        APP_IMAGES=docker.io/dustynv/vllm:0.8.6-r36.4-cu128-24.04 docker.io/dustynv/ollama:0.6.8-r36.4-cu126-22.04
  build-tegra-llm-image:
    runs-on: ubuntu-24.04-arm
    container:
      image: registry.access.redhat.com/ubi10/ubi
      options: --privileged --volume /:/host --volume containers:/var/lib/containers
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Get container tools in UBI builder
        run: dnf -y install podman buildah skopeo jq
      - name: Log in to the Container registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.DEST_REGISTRY_USER }}
          password: ${{ secrets.DEST_REGISTRY_PASSWORD }}
      - name: Pull container image
        run: |
          podman pull quay.io/redhat-et/rhel-bootc-tegra:base
      - name: Build raw image
        id: build-raw-img
        uses: osbuild/bootc-image-builder-action@v0.0.2
        with:
          config-file: ./tegra/config.toml
          image: quay.io/redhat-et/rhel-bootc-tegra:base
          types: |
            raw
