name: Test RHEL bootc image
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "tests/**"
      - ".github/workflows/tests.yml"
jobs:
  test-tegra-base-image:
    runs-on: ubuntu-24.04-arm
    container:
      image: registry.access.redhat.com/ubi10/ubi
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Test RHEL bootc image
        run: |
          dnf -y install podman

          uv venv
          uv pip install --extra-index-url https://pkg.jumpstarter.dev/main/simple jumpstarter-all

          mkdir -p ~/.config/jumpstarter/clients
          cat <<EOF > ~/.config/jumpstarter/clients/default.yaml
          ${{ secrets.JUMPSTARTER_CLIENT_CONFIG }}
          EOF
          uv run jmp config client use default

          uv run jmp shell --selector board=virtual -- pytest -s
