name: Test RHEL bootc image
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "tests/**"
      - ".github/workflows/tests.yml"
jobs:
  test-tegra-base-image:
    uses: ./.github/workflows/run-jumpstarter-workflow.yml
    secrets: inherit
    with:
      jumpstarter-selector: ${{ var.JUMPSTARTER_SELECTOR }}
      image-url: quay.io/redhat-et/rhel-bootc-tegra:base-raw
      workflow-cmd: pytest -s

  test-triton:
    uses: ./.github/workflows/run-jumpstarter-workflow.yml
    secrets: inherit
    needs: test-tegra-base-image
    with:
      jumpstarter-selector: ${{ vars.JUMPSTARTER_SELECTOR }}
      image-url: quay.io/redhat-et/rhel-bootc-tegra:triton-raw
      workflow-cmd: python3 inference/tests/jmp-test-triton.py

  test-microshift:
    uses: ./.github/workflows/run-jumpstarter-workflow.yml
    secrets: inherit
    needs: test-triton
    with:
      jumpstarter-selector: ${{ vars.JUMPSTARTER_SELECTOR }}
      workflow-cmd: python3 inference/tests/jmp-test-triton-microshift.py
      image-url: quay.io/redhat-et/rhel-bootc-tegra:triton-microshift-raw
